version: '3.8'
services:
  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mediatest
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# #   # pgadmin:
# #   #   image: dpage/pgadmin4
# #   #   ports:
# #   #     - 5433:80
# #   #   environment:
# #   #     POSTGRES_USER: username
# #   #     POSTGRES_PASSWORD: password
# #   #     POSTGRES_DB: mediatest
# #   #   depends_on:
# #   #     - database
# #   #   networks:
# #   #     - postgres-network
# #   #   volumes:
# #   #     - ./pgadmin-data/:/var/lib/pgadmin/

networks: 
  postgres-network:
    driver: bridge

# version: '3.8'

# services:
#   db:
#     image: mysql:latest
#     # command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: mediatest
#       MYSQL_USER: username
#       MYSQL_PASSWORD: password
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
#       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#       - ./db/my.cnf:/etc/mysql/my.cnf

# volumes:
#   mysql_data: